export const portfolioData = {
  personal: {
    name: "Samantha Sepeda",
    title: "Senior Software Engineer · Full Stack",
    location: "Singapore",
    email: "scsepeda@gmail.com",
    phone: "+65 8307 7475",
    linkedin: "https://linkedin.com/in/scsepeda",
    github: "https://github.com/scsepeda",
    summary: "I build and run .NET services and Angular applications for investment and banking technology in Singapore, most recently at GIC and Crédit Agricole CIB. I work end to end: REST APIs and microservices, ETL and batch pipelines, SQL Server and PostgreSQL, CI/CD and Kubernetes deployments, through to L3 production support.",
  },

  skills: {
    frontend: ["Angular", "React", "TypeScript", "JavaScript", "WPF"],
    backend: ["C#", ".NET / .NET Core", "ASP.NET", "Entity Framework", "Java", "Spring Boot", "Python", "VB.NET"],
    cloud: ["AWS (S3, SQS)", "Docker", "Kubernetes", "Helm", "OpenShift", "GitHub Actions", "GitLab CI", "ArgoCD", "SonarQube", "Snyk", "Datadog"],
    database: ["SQL Server", "PostgreSQL", "Redis", "Kafka", "Apache Spark", "Airflow", "OpenSearch"],
  },

  experience: [
    {
      id: 1,
      title: "Senior Software Engineer",
      company: "GIC Private Limited",
      location: "Singapore",
      period: "Sep 2025 – Present",
      current: true,
      description: "Building and supporting asset servicing applications that span back and middle office, across public- and private-market investments, on .NET Core, SQL Server and Entity Framework.",
      responsibilities: [
        "Implemented hedge swap transaction creation for private-market investments, integrating with an upstream investment platform",
        "L3 production support across private-investment modules, tracing issues through data, services and UI to root cause",
        "ETL and batch jobs feeding reporting, asset monitoring and valuation workflows",
        "Build and deployment pipelines with GitHub Actions, Docker, Kubernetes and Helm, monitored with Datadog",
        "Pull request reviews and pair programming to keep coding standards consistent",
      ],
      achievements: [],
    },
    {
      id: 2,
      title: "Senior Software Engineer",
      company: "Crédit Agricole CIB",
      location: "Singapore",
      period: "Mar 2020 – Sep 2025",
      current: false,
      description: "Five and a half years across three teams: desktop applications for Capital Markets P&L, Java and Spark ETL for Market Risk, then .NET Core and Angular full stack on the Compliance Data Hub, the microservices platform for compliance data management.",
      responsibilities: [
        "2022 – 2025 · Compliance Data Hub: .NET Core microservices, Angular, Kafka, PostgreSQL",
        "2021 – 2022 · Market Risk: Java and Spark ETL pipelines and batch jobs",
        "2020 – 2021 · Capital Markets P&L: VB.NET, .NET and WPF applications alongside Orchestrade",
        "Compliance and market data sources including FactSet, Thomson Reuters and Radar",
        "Designed CI/CD pipelines on GitLab with Docker, Kubernetes, ArgoCD, Vault and SonarQube",
        "Code reviews, pair programming and mentoring junior developers",
        "Acting tech lead for a team of 6–7 for 9 months: worked with product owners, architects and leads, and coordinated with DevOps, DBA, infrastructure and platform teams across France, Singapore and Mauritius",
        "Backup to the project manager: ran sprint planning and retrospectives",
        "Completed the platform handover to counterparts in Mauritius with knowledge transfer sessions",
      ],
      achievements: [
        { metric: "12+", description: "Microservices delivered for compliance tools used across 4 departments" },
        { metric: "65%", description: "Reduction in report generation time using Redis caching and SQL Server query optimisation" },
        { metric: "45%", description: "Fewer production issues after adding automated security and lint checks to CI/CD" },
        { metric: "9 months", description: "Covering sprint planning and retrospectives as backup to the project manager" },
        { metric: "300k", description: "Compliance data rows migrated between data centres" },
        { metric: "3rd Place", description: "Company-wide Gen AI Hackathon" },
      ],
    },
    {
      id: 3,
      title: "Technical Support Engineer",
      company: "NetSuite",
      location: "Makati, Philippines",
      period: "Aug 2018 – Mar 2020",
      current: false,
      description: "Tier 2 technical support for NetSuite ERP: debugged customer SuiteScript, Web Services and ODBC integrations, wrote knowledge base articles and documented recurring defects for the product development teams.",
      responsibilities: [],
      achievements: [
        { metric: "500+", description: "Support tickets closed with a 97% customer satisfaction rating" },
      ],
    },
    {
      id: 4,
      title: "Software Developer Intern",
      company: "Intellicare",
      location: "Makati, Philippines",
      period: "Sep 2017 – Dec 2017",
      current: false,
      description: "Built internal C# tools for the claims team on SQL Server and supported user acceptance testing.",
      responsibilities: [],
      achievements: [],
    },
    {
      id: 5,
      title: "Data Analyst Intern",
      company: "SGV & Co.",
      location: "Makati, Philippines",
      period: "Jun 2017 – Aug 2017",
      current: false,
      description: "Part of the data and fraud analysis team, managing and analysing EY data with SQL Server Management Studio and Tableau.",
      responsibilities: [],
      achievements: [],
    },
  ],

  projects: [
    {
      id: 1,
      title: "Compliance Data Hub",
      description: "Microservices platform for compliance data management at Crédit Agricole CIB. Delivered 12+ .NET Core services with Angular front ends, Kafka messaging between services and PostgreSQL storage, deployed on Kubernetes and used by 4 departments. Also migrated 300k rows of compliance data between data centres.",
      technologies: [".NET Core", "Angular", "Kafka", "PostgreSQL", "Docker", "Kubernetes"],
      highlights: ["2022 – 2025", "4 Departments"],
      type: "microservices",
    },
    {
      id: 2,
      title: "Market Risk ETL Pipelines",
      description: "Java and Apache Spark ETL pipelines for Market Risk data at Crédit Agricole CIB, with automated batch jobs for daily reporting and data synchronisation.",
      technologies: ["Java", "Apache Spark", "Batch Processing"],
      highlights: ["2021 – 2022", "Daily Batch"],
      type: "etl",
    },
    {
      id: 3,
      title: "CI/CD Pipeline with Automated Quality Gates",
      description: "Designed CI/CD pipelines on GitLab with Docker, Kubernetes, ArgoCD and Vault, adding SonarQube analysis plus automated security and lint checks before deployment. Production issues dropped by 45% afterwards.",
      technologies: ["GitLab CI", "Docker", "Kubernetes", "ArgoCD", "SonarQube", "Vault"],
      highlights: ["45% Fewer Issues", "Automated Checks"],
      type: "devops",
    },
    {
      id: 4,
      title: "Capital Markets P&L Applications",
      description: "Desktop applications for profit and loss tracking in the Capital Markets department at Crédit Agricole CIB, built in VB.NET, .NET and WPF and working alongside the Orchestrade trading platform.",
      technologies: ["VB.NET", ".NET", "WPF", "Orchestrade"],
      highlights: ["2020 – 2021", "Desktop"],
      type: "enterprise",
    },
  ],

  education: {
    degree: "Bachelor of Science in Information Technology",
    school: "University of Santo Tomas",
    location: "Manila, Philippines",
    period: "Jun 2014 – Aug 2018",
    honors: "Cum Laude",
    awards: [
      "3rd Place, Best Thesis (Web & Mobile Application Development Track)",
      "3rd Place, Accenture Program the Future 2017",
      "Top 1 Dean's Lister, 2015",
    ],
  },

  certifications: [
    {
      name: "IT Passport Certification",
      description: "Information Technology Fundamentals",
      icon: "passport",
    },
    {
      name: "IBM DB2 Academic Associate",
      description: "Database Management Certification",
      icon: "database",
    },
    {
      name: "Google Cloud Platform (GCP)",
      description: "Essential Training for Developers",
      icon: "cloud",
    },
  ],
};
